package com.shevay.knowledge.embedding;

import java.util.List;

/**
 * Provider-neutral domain interface for generating vector embeddings from text inputs.
 */
public interface EmbeddingProvider {

    /**
     * Generates a single L2-normalized Embedding vector for the given text and purpose.
     *
     * @param text    input text to embed
     * @param purpose semantic intent (DOCUMENT or QUERY)
     * @return L2-normalized Embedding value object
     */
    Embedding embed(String text, EmbeddingPurpose purpose);

    /**
     * Generates L2-normalized Embedding vectors for a batch of text inputs preserving order.
     *
     * @param texts   list of input texts
     * @param purpose semantic intent (DOCUMENT or QUERY)
     * @return ordered list of L2-normalized Embedding value objects
     */
    List<Embedding> embedBatch(List<String> texts, EmbeddingPurpose purpose);

    /**
     * Returns the output vector dimension generated by this provider.
     *
     * @return vector length (e.g. 768)
     */
    int getDimensions();

    /**
     * Returns the model identifier string used by this provider.
     *
     * @return model identifier (e.g. "gemini-embedding-001")
     */
    String getModelIdentifier();
}
