package com.shevay.knowledge.generation;

import java.util.Objects;

/**
 * Fake/Dummy LlmGenerationProvider for unit testing and offline CLI execution.
 * Returns deterministic text without network access or API credentials.
 */
public class DummyLlmGenerationProvider implements LlmGenerationProvider {

    private final String fixedResponse;
    private final String modelIdentifier;
    private int callCount;
    private String lastPrompt;

    public DummyLlmGenerationProvider() {
        this("This is a deterministic answer generated by DummyLlmGenerationProvider based on the provided context.", "dummy-llm");
    }

    public DummyLlmGenerationProvider(String fixedResponse) {
        this(fixedResponse, "dummy-llm");
    }

    public DummyLlmGenerationProvider(String fixedResponse, String modelIdentifier) {
        this.fixedResponse = Objects.requireNonNull(fixedResponse, "fixedResponse must not be null");
        this.modelIdentifier = Objects.requireNonNull(modelIdentifier, "modelIdentifier must not be null");
        this.callCount = 0;
    }

    @Override
    public String generate(String prompt) {
        if (prompt == null || prompt.isBlank()) {
            throw new IllegalArgumentException("Prompt must not be null or blank");
        }
        this.callCount++;
        this.lastPrompt = prompt;
        return fixedResponse;
    }

    @Override
    public String getModelIdentifier() {
        return modelIdentifier;
    }

    public int getCallCount() {
        return callCount;
    }

    public String getLastPrompt() {
        return lastPrompt;
    }
}
